version: "3.9"
services:
  postgres:
    image: postgres
    container_name: database_chatflow
    restart: always
    ports:
      - $DATABASE_PORT:5432
    hostname: $DATABASE_HOSTNAME
    environment:
      PUID: 1000
      PGID: 1000
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
        - ./scripts/postgres/init_sql.sh:/docker-entrypoint-initdb.d/init_sql.sh

  app:
    build:
      context: .
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: chatflow_backend
    restart: "unless-stopped"
    ports:
      - "3333:3333"
      - "9229:9229"
    volumes:
      - ./:/app
      - /app/node_modules
    links:
      - postgres
    depends_on:
      - postgres
