version: "3.9"
services:
  database:
    image: postgres
    container_name: database_chatflow
    restart: always
    ports:
      - $DATABASE_PORT:5432
    hostname: $DATABASE_HOSTNAME
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: chatflow_backend
    restart: always
    ports:
      - "3333:3000"
    volumes:
      - .:/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local