name: Build Docker

on:

  pull_request:
    branches:
      - main

jobs:
  build:
    workflow_run:
      workflows: [run-tsc, run-tests, run-build]
      types:
      - completed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: docker build -t chatflow:latest .
        working-directory: /app

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
