name: Build Docker

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    workflow_run:
      workflows: [run-tsc, run-tests, run-build]
      types:
        - completed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: echo ::set-output name=tag::$(git describe --abbrev=0)
        id: tag
        working-directory: .

      - name: Build
        run: yarn build

      - name: Build Docker Image
        run: docker build -t chatflow:${{ steps.tag.outputs.tag }}  .
        working-directory: .
