name: Build

on:


  pull_request:
    branches:
      - main

jobs:
  build:
    workflow_run:
      workflows: [run-tsc, run-tests]
      types:
      - completed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
